{
 "title": "Service A - Application & Envoy Metrics",
 "tags": [
  "fastapi",
  "service_a"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Envoy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests by HTTP Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"2..\"}[1m])) by (job, instance)",
     "legendFormat": "2xx - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"3..\"}[1m])) by (job, instance)",
     "legendFormat": "3xx - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"4..\"}[1m])) by (job, instance)",
     "legendFormat": "4xx - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"5..\"}[1m])) by (job, instance)",
     "legendFormat": "5xx - {{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Requests by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "reqps", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler=\"/pathA\"}[1m])) by (job, instance)",
     "legendFormat": "/pathA - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler=\"/pathB\"}[1m])) by (job, instance)",
     "legendFormat": "/pathB - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler=\"/error400\"}[1m])) by (job, instance)",
     "legendFormat": "/error400 - {{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(http_requests_total{handler=\"/error500\"}[1m])) by (job, instance)",
     "legendFormat": "/error500 - {{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Success Rate (2xx)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"2..\"}[1m])) / sum(rate(http_requests_total{handler!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"4..\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"5..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Application - Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 30 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{handler!=\"/metrics\",status=~\"[45]..\"}[1m])) / sum(rate(http_requests_total{handler!=\"/metrics\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])) by (le, job, instance))",
     "legendFormat": "p50 - {{job}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])) by (le, job, instance))",
     "legendFormat": "p95 - {{job}} - {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{handler!=\"/metrics\"}[1m])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Request Breakdown (Path + Status)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\"}[30s])) by (job, handler, status, instance)",
     "legendFormat": "{{handler}} - {{status}} - {{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Total Requests (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!=\"/metrics\"}[1h]))"
    }
   ]
  },
  {
   "title": "Envoy - Requests by Status Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "2xx - {{envoy_cluster_name}}"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "3xx - {{envoy_cluster_name}}"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "4xx - {{envoy_cluster_name}}"
    },
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "5xx - {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Requests by Backend Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "reqps", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Total Requests (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total[1h]))"
    }
   ]
  },
  {
   "title": "Envoy - Current Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_upstream_rq_total[1m]))"
    }
   ]
  },
  {
   "title": "Envoy - Error Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=~\"4|5\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_xx[1m]))"
    }
   ]
  },
  {
   "title": "Envoy - Request Breakdown (Cluster + Status)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_xx[30s])) by (envoy_cluster_name, envoy_response_code_class)",
     "legendFormat": "{{envoy_cluster_name}} - {{envoy_response_code_class}}xx"
    }
   ]
  },
  {
   "title": "Envoy - Total Requests by Backend Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "requests" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_total[30s])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Retry Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps", "label": "retries/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m])) by (envoy_cluster_name)",
     "legendFormat": "Retries - {{envoy_cluster_name}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m])) by (envoy_cluster_name)",
     "legendFormat": "Retry Success - {{envoy_cluster_name}}"
    },
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_overflow[1m])) by (envoy_cluster_name)",
     "legendFormat": "Retry Overflow - {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Envoy - Total Retries (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_retry[1h]))"
    }
   ]
  },
  {
   "title": "Envoy - Retry Success Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry_success[1m])) / sum(rate(envoy_cluster_upstream_rq_retry[1m]))"
    }
   ]
  },
  {
   "title": "Envoy - Current Retry Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 25 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_retry[1m]))"
    }
   ]
  },
  {
   "title": "Envoy - Retry Overflow (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_rq_retry_overflow[1h]))"
    }
   ]
  },
  { "title": "Rate Limiting Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Rate Limiting Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "reqps", "label": "requests/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enabled[1m]))",
     "legendFormat": "Total Checked"
    },
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_ok[1m]))",
     "legendFormat": "Allowed"
    },
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enforced[1m]))",
     "legendFormat": "Rate Limited"
    }
   ]
  },
  {
   "title": "Rate Limit Hit Rate",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enforced[1m])) / sum(rate(envoy_http_local_rate_limit_enabled[1m]))"
    }
   ]
  },
  {
   "title": "Rate Limited Requests (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_local_rate_limit_enforced[1h]))"
    }
   ]
  },
  {
   "title": "Total Requests Checked (Last Hour)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 55 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(envoy_http_local_rate_limit_enabled[1h]))"
    }
   ]
  },
  {
   "title": "Current Rate Limit Rejections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(envoy_http_local_rate_limit_enforced[1m]))"
    }
   ]
  }
 ]
}